#cloud-config

coreos:
  flannel:
    interface: $private_ipv4
    etcd_endpoints: "{{ .flannel_memberlist }}"
    etcd_certfile: /run/flannel/etcd-proxy.pem
    etcd_keyfile: /run/flannel/etcd-proxy-key.pem
    etcd_cafile: /etc/ssl/etcd/platform_ca.pem
  update:
    reboot-strategy: 'off'
  units:
  - name: systemd-sysctl.service
    command: restart
  - name: iptables-restore.service
    enable: true
    command: start
  - name: fleet.service
    enable: false
  - name: etcd2.service
    enable: false
    command: stop
  - name: update-engine.service
    command: stop
    enable: false
  - name: format-docker-volume.service
    command: start
    content: |
      [Unit]
      Description=Formats the docker volume
      After=dev-xvdd.device
      Requires=dev-xvdd.device
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/bash -c '/usr/sbin/blkid /dev/xvdd || (/usr/sbin/wipefs -f /dev/xvdd && /usr/sbin/mkfs.ext4 /dev/xvdd)'
  - name: var-lib-docker.mount
    command: start
    enable: true
    content: |
      [Unit]
      Description=Mount docker volume
      Requires=format-docker-volume.service
      After=format-docker-volume.service
      Before=docker.service
      [Mount]
      What=/dev/xvdd
      Where=/var/lib/docker
      Type=ext4
  - name: docker.service
    drop-ins:
    - name: 10-opts.conf
      content: |
        [Service]
        Environment="DOCKER_OPTS=--iptables=false --log-opt max-size=100m --log-opt max-file=1 --default-ulimit=nofile=32768:32768 --default-ulimit=nproc=16384:16384"
    {{ if is_true .enable_calico -}}
    - name: 40-flannel.conf
      content: |
        [Unit]
        Requires=flanneld.service
        After=flanneld.service
        [Service]
        ExecStartPre=/usr/bin/cp /run/flannel_docker_opts.env /etc/kubernetes/cni/docker_opts_cni.env{{ end }}
  - name: flanneld.service
    command: start
    enable: true
    drop-ins:
    - name: 100-etcd-certificates.conf
      content: |
        [Service]
        RestartSec=30
        Restart=always
        EnvironmentFile=/etc/kmsctl

        ExecStartPre=/usr/bin/systemctl --quiet is-active install-kmsctl.service
        ExecStartPre=/usr/bin/systemctl --quiet is-active update-ca-certificates.service
        ExecStartPre=/opt/bin/kmsctl get --output-dir=/run/flannel --recursive=true common/
  - name: install-kmsctl.service
    command: start
    content: |
      [Unit]
      Description=Install kmsctl
      Documentation=https://github.com/gambol99/kmsctl

      [Service]
      Type=notify
      NotifyAccess=all
      RemainAfterExit=yes
      TimeoutStartSec=180
      Environment="URL={{ .kmsctl_release_url }}"
      Environment="FILE=/opt/bin/kmsctl"
      Environment="MD5SUM={{ .kmsctl_release_md5 }}"
      ExecStartPre=/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/bash -c 'until [[ -x ${FILE} ]] && [[ $(md5sum ${FILE} | cut -f1 -d" ") == ${MD5SUM} ]]; do wget -q -O ${FILE}.gz ${URL} && gunzip ${FILE}.gz && chmod +x ${FILE}; done'
      ExecStart=/usr/bin/systemd-notify --ready --status="succussfully downloaded the kmsctl"
  - name: update-ca-certificates.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Update CA Certificates
      Requires=install-kmsctl.service
      After=install-kmsctl.service

      [Service]
      Type=notify
      NotifyAccess=all
      EnvironmentFile=/etc/environment
      EnvironmentFile=/etc/kmsctl
      RemainAfterExit=yes
      TimeoutStartSec=300
      ExecStartPre=/usr/bin/mkdir -p /etc/ssl/etcd
      ExecStartPre=/opt/bin/kmsctl get --output-dir=/etc/ssl/certs common/platform_ca.pem
      ExecStartPre=/usr/bin/cp -f /etc/ssl/certs/platform_ca.pem /etc/ssl/etcd/platform_ca.pem
      ExecStartPre=/usr/sbin/update-ca-certificates
      ExecStart=/usr/bin/systemd-notify --ready --status="succussfully updated the ca root certificates"
  - name: kubelet.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes Kubelet
      Documentation=https://github.com/GoogleCloudPlatform/kubernetes

      [Service]
      Restart=always
      RestartSec=10
      RuntimeDirectory=kubelet
      RuntimeDirectoryMode=0700
      Environment=KUBELET_IMAGE_TAG={{ .kubernetes_version }}
      Environment=KUBELET_IMAGE_URL={{ .kubernetes_image }}
      EnvironmentFile=/etc/kmsctl
      EnvironmentFile=/etc/environment
      Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
        --volume dns,kind=host,source=/etc/resolv.conf \
        --mount volume=dns,target=/etc/resolv.conf \
        --mount volume=etc-ssl-certs,target=/etc/ssl/certs \
        --mount volume=stage,target=/tmp \
        --mount volume=var-lib-rkt,target=/var/lib/rkt \
        --mount volume=var-log,target=/var/log \
        --volume stage,kind=host,source=/tmp \
        --volume var-lib-rkt,kind=host,source=/var/lib/rkt \
        --volume var-log,kind=host,source=/var/log \
        --volume etc-ssl-certs,kind=host,source=/etc/ssl/certs \
        --volume cni-bin,kind=host,source=/opt/cni/bin \
        --mount volume=cni-bin,target=/opt/cni/bin"

      ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
      ExecStartPre=/usr/sbin/modprobe br_netfilter
      ExecStartPre=/usr/bin/systemctl --quiet is-active update-ca-certificates.service
      ExecStartPre=/usr/bin/systemctl --quiet is-active flanneld.service
      ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests /opt/cni/bin
      ExecStartPre=/opt/bin/kmsctl get --output-dir=%t/kubelet --recursive=true compute/kubeconfig_kubelet
      ExecStart=/usr/lib/coreos/kubelet-wrapper \
        --address=0.0.0.0 \
        --allow-privileged=true \
        --cloud-config=/etc/kubernetes/cloud.cfg \
        --cloud-provider=aws \
        --cluster-dns=10.200.0.10 \
        --cluster-domain=cluster.local \
        {{- if is_true .enable_calico -}}
        --cni-conf-dir=/etc/kubernetes/cni/net.d \{{ end }}
        --cpu-cfs-quota=true \
        --host-network-sources=* \
        --hostname-override=${COREOS_PRIVATE_IPV4} \
        --image-gc-high-threshold=60 \
        --image-gc-low-threshold=40 \
        --kube-reserved=cpu=25m,memory=50Mi \
        --kubeconfig=%t/kubelet/kubeconfig_kubelet \
        --logtostderr=true \
        {{- if is_true .enable_calico -}}
        --network-plugin=cni \{{ end }}
        --node-labels="{{ .labels }}" \
        --pod-manifest-path=/etc/kubernetes/manifests \
        --rkt-path=/usr/bin/rkt \
        --rkt-stage1-image=coreos.com/rkt/stage1-coreos \
        --require-kubeconfig=true \
        --system-reserved=cpu=50m,memory=100Mi
write_files:
- path: /etc/kmsctl
  content: |
    AWS_S3_BUCKET={{ .secrets_bucket_name }}
    AWS_DEFAULT_REGION={{ .aws_region }}
- path: /etc/aws-environment
  content: |
    AWS_REGION={{ .aws_region }}
    DNS_ZONE_NAME={{ .private_zone_name }}
    ENVIRONMENT={{ .environment }}
- path: /etc/kubernetes/cloud.cfg
  permissions: 0444
  content: |
    [Global]
    KubernetesClusterTag = "{{ .environment }}"
    DisableSecurityGroupIngress = true
{{ if is_true .enable_calico -}}
- path: /etc/kubernetes/cni/net.d/10-flannel.conf
  permissions: 0444
  owner: root
  content: |
    {
      "name": "podnet",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }{{ end }}
- path: /etc/kubernetes/manifests/kube-manifests.yml
  permissions: 0444
  owner: root
  content: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: kube-manifests
      namespace: kube-system
    spec:
      hostNetwork: true
      containers:
      - name: manifests
        image: {{ .kmsctl_image }}
        args:
        - --region={{ .aws_region }}
        - get
        - --output-dir=/etc/kubernetes/manifests
        - --bucket={{ .secrets_bucket_name }}
        - --sync=true
        - --sync-interval=1m
        - --recursive=true
        - manifests/compute/{{ .compute_name }}
        volumeMounts:
        - name: manifests
          mountPath: /etc/kubernetes/manifests
      volumes:
      - name: manifests
        hostPath:
          path: /etc/kubernetes/manifests
- path: /var/lib/iptables/rules-save
  content: |
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    -A FORWARD -d 169.254.169.254/32 -i docker0 -p tcp -m tcp -j DROP
    -A FORWARD -i docker0 -p tcp -m tcp --dport 2379 -j DROP
    :OUTPUT ACCEPT [0:0]
    COMMIT

- path: /etc/sysctl.d/10-disable-ipv6.conf
  permissions: 0644
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6 = 1
